---
- name: Create directory
  file:
    dest: /opt/snmp_exporter
    state: directory

- name: Download snmp exporter binary to local folder
  become: no
  unarchive:
    src: "https://github.com/prometheus/snmp_exporter/releases/download/v{{ snmp_exporter_version }}/snmp_exporter-{{ snmp_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/snmp_exporter-{{ snmp_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/snmp_exporter"
  delegate_to: localhost

- name: Propagate SNMP Exporter binaries
  copy:
    src: "/tmp/snmp_exporter-{{ snmp_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/snmp_exporter"
    dest: "/opt/snmp_exporter"
    mode: 0755
  notify:
    - restart snmp exporter

- name: Copy the SNMP Exporter systemd service file
  template:
    src: snmp_exporter.service.j2
    dest: /etc/systemd/system/snmp_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart snmp exporter

- name: Copy configuration file
  copy:
    src: "{{ snmp_exporter_config_file }}"
    dest: /opt/snmp_exporter/snmp.yml
  notify:
    - restart snmp exporter

- name: Ensure SNMP Exporter is enabled on boot
  service:
    name: snmp_exporter
    enabled: yes
    use: service
